name: example
description: Example App for 'editors' package

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # combos: ^1.0.0+2
  combos: any
  editors: any
  demo_items:
    git: https://github.com/creomobile/demo_items

dependency_overrides:
  editors:
    path: ../
  combos:
    git:
      url: https://github.com/creomobile/combos
      ref: 1.1.0

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
