name: editors
description: Simple Flutter Editors including StringEditor, IntEditor, EnumEditor, BoolEditor
version: 0.0.11
homepage: https://github.com/creomobile/editors

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  titles: 0.0.4
  combos: ^1.2.0
  calendart: ^1.0.5
  creo_color_picker: ^0.0.4

dev_dependencies:
  pedantic: ^1.8.0

flutter:
