name: editors
description: Simple Flutter Editors including StringEditor, IntEditor, EnumEditor, BoolEditor
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0

flutter:
