name: editors
description: Simple Flutter Editors including StringEditor, IntEditor, EnumEditor, BoolEditor
version: 0.0.2+1
homepage: https://github.com/creomobile/editors

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  combos: ^1.0.0+2

dev_dependencies:
  pedantic: ^1.8.0

flutter:
